# VIA LOCALHOST

### GET start from scratch
curl http://localhost:50000/aquaicu?message=Restart&from=4500000000

### GET confirm starting new iteration
curl http://localhost:50000/aquaicu?message=Yes&from=4500000000

### GET valid response to items
curl http://localhost:50000/aquaicu?message=2&from=4500000000

### GET invalid response to items
curl http://localhost:50000/aquaicu?message=10&from=4500000000

### GET fetch health of FastAPI service
curl http://localhost:50000/health
